server:
  port: 8080
spring:
  devtools:
    remote:
      restart:
        enabled: true
  datasource:
    password: root
    username: root
    url:     jdbc:mysql://localhost:3306/test_db?autoReconnect=true&useSSL=false

---

spring:
  profiles: test
