export const FETCH_BOARD_LIST_SUCCESS = 'Boards/FETCH_BOARD_LIST_SUCCESS';
export const UPDATE_BOARD_SUCCESS = 'Boards/UPDATE_BOARD_SUCCESS';
export const DELETE_BOARD_SUCCESS = 'Boards/DELETE_BOARD_SUCCESS';
export const CREATE_BOARD_SUCCESS = 'Boards/CREATE_BOARD_SUCCESS';

export const FETCH_TASKS_FOR_BOARD_SUCCESS = 'Boards/FETCH_TASKS_FOR_BOARD_SUCCESS';

export const FETCH_TASK_SUCCESS = 'Tasks/FETCH_TASK_SUCCESS';
export const CREATE_TASK_SUCCESS = 'Tasks/CREATE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'Tasks/UPDATE_TASK_SUCCESS';
export const DELETE_TASK_SUCCESS = 'Tasks/DELETE_TASK_SUCCESS';
