export const FETCH_BOARD_LIST_SUCCESS = 'Boards/FETCH_BOARD_LIST_SUCCESS';
export const DELETE_BOARD_SUCCESS = 'Boards/DELETE_BOARD_SUCCESS';
export const FETCH_TASK_SUCCESS = 'Boards/FETCH_TASK_SUCCESS';
