server:
  port: 8080
spring:
  data:
    mongodb:
      database: boards_db
      uri: mongodb://localhost:27017
  devtools:
    remote:
      restart:
        enabled: true

---

spring:
  profiles: test
