server:
  port: 8080
spring:
  data:
    mongodb:
      database: boards_db
  devtools:
    remote:
      restart:
        enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
app.build-number: qwe
application.title: Agile-boards
application.version: 0.1
---


spring:
  profiles: test
