server:
  port: 8080
spring:
  data:
    mongodb:
      repositories:
        type: auto
  devtools:
    remote:
      restart:
        enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
app.build-number: 1
application.title: Agile-boards
application.version: 0.1

---

spring:
  profiles: dev
  data:
    mongodb:
      database: boards_db
